In [1]:
import numpy as np 
import pandas as pd

더미데이터 추가(movie.csv)

In [4]:
meta = pd.read_csv('./sample_data/movie.csv')
meta.head()

  user_id movie_code title  rating     genres
0    id00        m01   t01       8  animation
1    id00        m02   t02       3     comedy
2    id00        m03   t03      10      drama
3    id00        m04   t04       1    romance
4    id00        m05   t05       6     action

피어슨 상관계수 산출을 위한 피벗데이블 생성

In [7]:
matrix = meta.pivot_table(index='user_id', columns='title', values='rating')
matrix.head(20)

title    t01  t02   t03  t04  t05  t06  t07  ...  t71  t72  t73  t74  t75  t76  t77
user_id                                      ...
id00     8.0  3.0  10.0  1.0  6.0  5.0  9.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id01     NaN  NaN   NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id02     9.0  9.0   5.0  6.0  5.0  4.0  2.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id03     NaN  NaN   NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id04     NaN  NaN   NaN  NaN  NaN  8.0  0.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id05     NaN  NaN   NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id06     NaN  NaN   4.0  1.0  5.0  1.0  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id07     NaN  NaN   NaN  NaN  NaN  NaN  9.0  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id08     NaN  NaN   NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
id09     NaN  NaN   NaN  NaN  NaN  NaN  NaN  ...  3.0  7.0  4.0  6.0  4.0  2.0  6.0

[10 rows x 77 columns]

피어슨 상관관계 분석

In [13]:
GENRE_WEIGHT = 0.1

def pearsonR(s1, s2):
    s1_c = s1 - s1.mean()
    s2_c = s2 - s2.mean()
    return np.sum(s1_c * s2_c) / np.sqrt(np.sum(s1_c ** 2) * np.sum(s2_c ** 2))
    # 분모가 클수록 상관관계가 떨어지고, 분자가 클수록 상관관계가 높아짐

# 추천함수 생성
def recommend(input_movie, matrix, n, similar_genre=True):
    input_genres = meta[meta['title'] == input_movie]['genres'].iloc(0)[0]

    result = []
    for title in matrix.columns:
        if title == input_movie:
            # 같은 영화를 추천받는 경우는 건너뜀
            continue

        # rating comparison
        cor = pearsonR(matrix[input_movie], matrix[title])
        
        # genre comparison
        if similar_genre and len(input_genres) > 0:
            temp_genres = meta[meta['title'] == title]['genres'].iloc(0)[0]
            # 현재 비교하고 있는 영화
            same_count = np.sum(np.isin(input_genres, temp_genres))
            # Input으로 넣은 영화와 비교
            # np.isin() -> 배열을 비교하여 똑같은 요소가 있으면 True를 반환
            cor += (GENRE_WEIGHT * same_count)
        
        if np.isnan(cor):
            continue
        else:
            result.append((title, '{:.2f}'.format(cor), temp_genres))
            
    result.sort(key=lambda r: r[1], reverse=True)
    # 리스트 정렬

    return result[:n]

추천 영화

In [14]:
recommend_result = recommend('t20', matrix, 5, similar_genre=True)
# t20 영화를 보고 추천영화 5개를 선정
pd.DataFrame(recommend_result, columns = ['Title', 'Correlation', 'Genre'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars

  Title Correlation            Genre
0   t09        0.79  science fiction
1   t24        0.74            drama
2   t36        0.48          romance
3   t38        0.48          romance
4   t43        0.48          romance